[project]
name = "tryoffset"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.117.1",
    "psycopg2-binary>=2.9.10",
    "uvicorn>=0.37.0",
]
